# backend/app/core/file_manager.py
import os
import json
from typing import Dict, List
from datetime import datetime

from app.config import settings


class FileManager:
    """Manages all output file generation."""

    def __init__(self, output_dir: str = None):
        self.output_dir = output_dir or settings.OUTPUT_DIR
        os.makedirs(self.output_dir, exist_ok=True)

    def create_project_structure(self, project_name: str) -> str:
        """Create full project directory structure."""
        project_dir = os.path.join(self.output_dir, project_name)
        dirs = [
            "",
            "src",
            "src/data",
            "src/models",
            "src/features",
            "src/visualization",
            "tests",
            "notebooks",
            "output",
            "output/models",
            "output/reports",
            "output/figures",
            "data",
            "data/raw",
            "data/processed",
            ".github/workflows",
        ]
        for d in dirs:
            os.makedirs(os.path.join(project_dir, d), exist_ok=True)

        return project_dir

    def write_file(self, project_dir: str, filepath: str, content: str):
        full_path = os.path.join(project_dir, filepath)
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        with open(full_path, "w", encoding="utf-8") as f:
            f.write(content)
        return full_path

    def generate_readme(self, project_info: Dict) -> str:
        return f"""# {project_info.get('name', 'DS-Copilot Project')}

> Auto-generated by DS-Copilot 🤖

## 📋 Overview
{project_info.get('description', 'Machine Learning project')}

## 📊 Dataset
- **Source**: {project_info.get('dataset_source', 'N/A')}
- **Shape**: {project_info.get('dataset_shape', 'N/A')}
- **Features**: {project_info.get('num_features', 'N/A')}
- **Target**: {project_info.get('target_column', 'N/A')}
- **Task Type**: {project_info.get('task_type', 'N/A')}

## 🧹 Data Cleaning
{project_info.get('cleaning_summary', 'See src/data/clean.py')}

## 📈 EDA Highlights
{project_info.get('eda_summary', 'See notebooks/eda.ipynb')}

## 🤖 Models Trained
{project_info.get('models_summary', 'See src/models/')}

## 📊 Results
| Model | Accuracy | F1 Score | Training Time |
|-------|----------|----------|---------------|
{project_info.get('results_table', '| - | - | - | - |')}

## 🚀 Quick Start
```bash
pip install -r requirements.txt
python src/train.py
```

## 📁 Project Structure
```
├── src/
│   ├── data/          # Data loading & cleaning
│   ├── features/      # Feature engineering
│   ├── models/        # Model training & evaluation
│   └── visualization/ # Plotting utilities
├── tests/             # Unit tests
├── notebooks/         # Jupyter notebooks
├── output/            # Generated artifacts
│   ├── models/        # Saved models
│   ├── reports/       # HTML/PDF reports
│   └── figures/       # Plots & charts
└── data/
    ├── raw/           # Original data
    └── processed/     # Cleaned data
```

## ⚙️ Generated by
DS-Copilot v1.0 | {datetime.now().strftime('%Y-%m-%d %H:%M')}
"""

    def generate_plan(self, steps: List[Dict]) -> str:
        plan = "# 📋 Execution Plan\n\n"
        plan += f"> Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n"

        for i, step in enumerate(steps, 1):
            status_icon = {
                "completed": "✅",
                "running": "🔄",
                "failed": "❌",
                "pending": "⏳",
            }.get(step.get("status", "pending"), "⏳")

            plan += f"## Step {i}: {step['name']} {status_icon}\n\n"
            plan += f"**Agent**: {step.get('agent', 'N/A')}\n"
            plan += f"**Status**: {step.get('status', 'pending')}\n"
            if step.get("description"):
                plan += f"**Description**: {step['description']}\n"
            if step.get("execution_time"):
                plan += f"**Time**: {step['execution_time']:.2f}s\n"
            plan += "\n---\n\n"

        return plan

    def generate_requirements(self, packages: List[str] = None) -> str:
        default_packages = [
            "pandas>=2.0.0",
            "numpy>=1.24.0",
            "scikit-learn>=1.3.0",
            "matplotlib>=3.7.0",
            "seaborn>=0.12.0",
            "xgboost>=2.0.0",
            "lightgbm>=4.0.0",
            "plotly>=5.15.0",
            "openpyxl>=3.1.0",
            "sqlalchemy>=2.0.0",
            "joblib>=1.3.0",
            "pytest>=7.4.0",
        ]
        if packages:
            default_packages.extend(packages)

        return "\n".join(sorted(set(default_packages)))

    def generate_dockerfile(self, project_name: str) -> str:
        return f"""FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PROJECT_NAME={project_name}

CMD ["python", "src/train.py"]
"""

    def get_file_tree(self, project_dir: str) -> Dict:
        """Get project file tree as nested dict."""
        tree = {}
        for root, dirs, files in os.walk(project_dir):
            # Skip hidden dirs except .github
            dirs[:] = [
                d for d in dirs
                if not d.startswith(".") or d == ".github"
            ]
            rel_root = os.path.relpath(root, project_dir)
            current = tree
            if rel_root != ".":
                for part in rel_root.split(os.sep):
                    current = current.setdefault(part, {})
            for f in files:
                current[f] = None  # None = file
        return tree
